//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsisAppTransportService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBilling", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    public partial class OrdBilling : object
    {
        
        private string AddressNameField;
        
        private string AddressNumberField;
        
        private string AgentCodeField;
        
        private string AmphurField;
        
        private long BillIDField;
        
        private IsisAppTransportService.OrdBillingDue[] BillingDuesField;
        
        private IsisAppTransportService.OrdBillingPayBy BillingPayByField;
        
        private string CertificateNumberField;
        
        private string FirstNameField;
        
        private string IDCardNumberField;
        
        private System.DateTime InstallDateField;
        
        private System.DateTime IssueDateField;
        
        private string LastNameField;
        
        private string MoohField;
        
        private int NeedToRearrangeContentField;
        
        private string PassportNumberField;
        
        private int PayModeField;
        
        private string PhoneNumberField;
        
        private System.DateTime PolicyDateField;
        
        private string PolicyNumberField;
        
        private string PreNameField;
        
        private string ProvinceField;
        
        private string RoadField;
        
        private string SoiField;
        
        private string TambolField;
        
        private string UserIDField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressName
        {
            get
            {
                return this.AddressNameField;
            }
            set
            {
                this.AddressNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressNumber
        {
            get
            {
                return this.AddressNumberField;
            }
            set
            {
                this.AddressNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentCode
        {
            get
            {
                return this.AgentCodeField;
            }
            set
            {
                this.AgentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amphur
        {
            get
            {
                return this.AmphurField;
            }
            set
            {
                this.AmphurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillID
        {
            get
            {
                return this.BillIDField;
            }
            set
            {
                this.BillIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IsisAppTransportService.OrdBillingDue[] BillingDues
        {
            get
            {
                return this.BillingDuesField;
            }
            set
            {
                this.BillingDuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IsisAppTransportService.OrdBillingPayBy BillingPayBy
        {
            get
            {
                return this.BillingPayByField;
            }
            set
            {
                this.BillingPayByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateNumber
        {
            get
            {
                return this.CertificateNumberField;
            }
            set
            {
                this.CertificateNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCardNumber
        {
            get
            {
                return this.IDCardNumberField;
            }
            set
            {
                this.IDCardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InstallDate
        {
            get
            {
                return this.InstallDateField;
            }
            set
            {
                this.InstallDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate
        {
            get
            {
                return this.IssueDateField;
            }
            set
            {
                this.IssueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mooh
        {
            get
            {
                return this.MoohField;
            }
            set
            {
                this.MoohField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NeedToRearrangeContent
        {
            get
            {
                return this.NeedToRearrangeContentField;
            }
            set
            {
                this.NeedToRearrangeContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber
        {
            get
            {
                return this.PassportNumberField;
            }
            set
            {
                this.PassportNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayMode
        {
            get
            {
                return this.PayModeField;
            }
            set
            {
                this.PayModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyDate
        {
            get
            {
                return this.PolicyDateField;
            }
            set
            {
                this.PolicyDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreName
        {
            get
            {
                return this.PreNameField;
            }
            set
            {
                this.PreNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road
        {
            get
            {
                return this.RoadField;
            }
            set
            {
                this.RoadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soi
        {
            get
            {
                return this.SoiField;
            }
            set
            {
                this.SoiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tambol
        {
            get
            {
                return this.TambolField;
            }
            set
            {
                this.TambolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBillingPayBy", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    public partial class OrdBillingPayBy : object
    {
        
        private string FirstNameField;
        
        private string IDCardNumberField;
        
        private string LastNameField;
        
        private string PassportNumberField;
        
        private string PreNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCardNumber
        {
            get
            {
                return this.IDCardNumberField;
            }
            set
            {
                this.IDCardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber
        {
            get
            {
                return this.PassportNumberField;
            }
            set
            {
                this.PassportNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreName
        {
            get
            {
                return this.PreNameField;
            }
            set
            {
                this.PreNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBillingDue", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    public partial class OrdBillingDue : object
    {
        
        private System.DateTime BillDateField;
        
        private long BillDueIDField;
        
        private string BillNumberField;
        
        private IsisAppTransportService.OrdBillingCancel BillingCancelField;
        
        private IsisAppTransportService.OrdBillingPlan[] BillingPlansField;
        
        private string BillingRemarkField;
        
        private System.DateTime DueDateField;
        
        private int PolicyLotField;
        
        private int PolicyYearField;
        
        private string PremiumTypeField;
        
        private string TaxRemarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BillDate
        {
            get
            {
                return this.BillDateField;
            }
            set
            {
                this.BillDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillDueID
        {
            get
            {
                return this.BillDueIDField;
            }
            set
            {
                this.BillDueIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNumber
        {
            get
            {
                return this.BillNumberField;
            }
            set
            {
                this.BillNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IsisAppTransportService.OrdBillingCancel BillingCancel
        {
            get
            {
                return this.BillingCancelField;
            }
            set
            {
                this.BillingCancelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IsisAppTransportService.OrdBillingPlan[] BillingPlans
        {
            get
            {
                return this.BillingPlansField;
            }
            set
            {
                this.BillingPlansField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingRemark
        {
            get
            {
                return this.BillingRemarkField;
            }
            set
            {
                this.BillingRemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyLot
        {
            get
            {
                return this.PolicyLotField;
            }
            set
            {
                this.PolicyLotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyYear
        {
            get
            {
                return this.PolicyYearField;
            }
            set
            {
                this.PolicyYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PremiumType
        {
            get
            {
                return this.PremiumTypeField;
            }
            set
            {
                this.PremiumTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxRemark
        {
            get
            {
                return this.TaxRemarkField;
            }
            set
            {
                this.TaxRemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBillingCancel", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    public partial class OrdBillingCancel : object
    {
        
        private string BillNumberField;
        
        private int CancelTypeField;
        
        private string ReasonCodeField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNumber
        {
            get
            {
                return this.BillNumberField;
            }
            set
            {
                this.BillNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CancelType
        {
            get
            {
                return this.CancelTypeField;
            }
            set
            {
                this.CancelTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdBillingPlan", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    public partial class OrdBillingPlan : object
    {
        
        private int AssureYearField;
        
        private long BillPlanIDField;
        
        private decimal EFPremiumField;
        
        private decimal EMPremiumField;
        
        private int PayYearField;
        
        private string PlanBlockField;
        
        private string PlanCodeField;
        
        private string PlanCode2Field;
        
        private string PlanTypeField;
        
        private decimal PremiumField;
        
        private decimal SummField;
        
        private decimal TaxPremiumField;
        
        private decimal XOCPPremiumField;
        
        private decimal XTRPremiumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssureYear
        {
            get
            {
                return this.AssureYearField;
            }
            set
            {
                this.AssureYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillPlanID
        {
            get
            {
                return this.BillPlanIDField;
            }
            set
            {
                this.BillPlanIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EFPremium
        {
            get
            {
                return this.EFPremiumField;
            }
            set
            {
                this.EFPremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EMPremium
        {
            get
            {
                return this.EMPremiumField;
            }
            set
            {
                this.EMPremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayYear
        {
            get
            {
                return this.PayYearField;
            }
            set
            {
                this.PayYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanBlock
        {
            get
            {
                return this.PlanBlockField;
            }
            set
            {
                this.PlanBlockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanCode
        {
            get
            {
                return this.PlanCodeField;
            }
            set
            {
                this.PlanCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanCode2
        {
            get
            {
                return this.PlanCode2Field;
            }
            set
            {
                this.PlanCode2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanType
        {
            get
            {
                return this.PlanTypeField;
            }
            set
            {
                this.PlanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Premium
        {
            get
            {
                return this.PremiumField;
            }
            set
            {
                this.PremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Summ
        {
            get
            {
                return this.SummField;
            }
            set
            {
                this.SummField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxPremium
        {
            get
            {
                return this.TaxPremiumField;
            }
            set
            {
                this.TaxPremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal XOCPPremium
        {
            get
            {
                return this.XOCPPremiumField;
            }
            set
            {
                this.XOCPPremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal XTRPremium
        {
            get
            {
                return this.XTRPremiumField;
            }
            set
            {
                this.XTRPremiumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PensionGoal", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    public partial class PensionGoal : object
    {
        
        private decimal PayModeField;
        
        private string RecurringTypeField;
        
        private decimal TotalGoalUnitField;
        
        private decimal UnitPerTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PayMode
        {
            get
            {
                return this.PayModeField;
            }
            set
            {
                this.PayModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecurringType
        {
            get
            {
                return this.RecurringTypeField;
            }
            set
            {
                this.RecurringTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalGoalUnit
        {
            get
            {
                return this.TotalGoalUnitField;
            }
            set
            {
                this.TotalGoalUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPerTime
        {
            get
            {
                return this.UnitPerTimeField;
            }
            set
            {
                this.UnitPerTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BenefitItem", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    public partial class BenefitItem : object
    {
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string NotesField;
        
        private string OtherNameField;
        
        private decimal PercentageField;
        
        private string PreNameField;
        
        private string RelationshipField;
        
        private decimal SeqNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherName
        {
            get
            {
                return this.OtherNameField;
            }
            set
            {
                this.OtherNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Percentage
        {
            get
            {
                return this.PercentageField;
            }
            set
            {
                this.PercentageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreName
        {
            get
            {
                return this.PreNameField;
            }
            set
            {
                this.PreNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Relationship
        {
            get
            {
                return this.RelationshipField;
            }
            set
            {
                this.RelationshipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SeqNumber
        {
            get
            {
                return this.SeqNumberField;
            }
            set
            {
                this.SeqNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    public partial class Address : object
    {
        
        private string AddressNameField;
        
        private string AddressNumberField;
        
        private decimal AddressTypeField;
        
        private string AmphurField;
        
        private IsisAppTransportService.AddrContact ContactField;
        
        private string MoohField;
        
        private string ProvinceField;
        
        private string RoadField;
        
        private string SoiField;
        
        private string TambolField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressName
        {
            get
            {
                return this.AddressNameField;
            }
            set
            {
                this.AddressNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressNumber
        {
            get
            {
                return this.AddressNumberField;
            }
            set
            {
                this.AddressNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AddressType
        {
            get
            {
                return this.AddressTypeField;
            }
            set
            {
                this.AddressTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amphur
        {
            get
            {
                return this.AmphurField;
            }
            set
            {
                this.AmphurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IsisAppTransportService.AddrContact Contact
        {
            get
            {
                return this.ContactField;
            }
            set
            {
                this.ContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mooh
        {
            get
            {
                return this.MoohField;
            }
            set
            {
                this.MoohField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road
        {
            get
            {
                return this.RoadField;
            }
            set
            {
                this.RoadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soi
        {
            get
            {
                return this.SoiField;
            }
            set
            {
                this.SoiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tambol
        {
            get
            {
                return this.TambolField;
            }
            set
            {
                this.TambolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddrContact", Namespace="http://schemas.datacontract.org/2004/07/AppTransport.DataContract", IsReference=true)]
    public partial class AddrContact : object
    {
        
        private string EMailField;
        
        private string FaxField;
        
        private string HomePhoneField;
        
        private string MobilePhoneField;
        
        private string OfficePhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail
        {
            get
            {
                return this.EMailField;
            }
            set
            {
                this.EMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone
        {
            get
            {
                return this.HomePhoneField;
            }
            set
            {
                this.HomePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone
        {
            get
            {
                return this.MobilePhoneField;
            }
            set
            {
                this.MobilePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficePhone
        {
            get
            {
                return this.OfficePhoneField;
            }
            set
            {
                this.OfficePhoneField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://NewISISService/2012/ISISAppTransportService", ConfigurationName="IsisAppTransportService.IAppTransportServiceContract")]
    public interface IAppTransportServiceContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeAppFormStatus", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeAppFormStatusResponse")]
        System.Threading.Tasks.Task ChangeAppFormStatusAsync(string appRegisterID, string status, string subStatus, string detail, System.DateTime requestDate, int gracePeriod, long isisDocID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etAppFormContentByID", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etAppFormContentByIDResponse")]
        System.Threading.Tasks.Task<byte[]> GetAppFormContentByIDAsync(string appRegisterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etMoreContentByID", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etMoreContentByIDResponse")]
        System.Threading.Tasks.Task<byte[]> GetMoreContentByIDAsync(string responseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etContentByID", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etContentByIDResponse")]
        System.Threading.Tasks.Task<byte[]> GetContentByIDAsync(string contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endCompleteContentStatus", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endCompleteContentStatusResponse")]
        System.Threading.Tasks.Task SendCompleteContentStatusAsync(string appRegisterID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endReceiveContentStatusToOutSide", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endReceiveContentStatusToOutSideResponse")]
        System.Threading.Tasks.Task SendReceiveContentStatusToOutSideAsync(string appRegisterID, string isisDocID, string receiveBranchCode, string createdBy, string contentID);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToIssueNewPolicy", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToIssueNewPolicyResponse")]
        System.Threading.Tasks.Task<IsisAppTransportService.RequestToIssueNewPolicyResponse> RequestToIssueNewPolicyAsync(IsisAppTransportService.RequestToIssueNewPolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToCancelBill", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToCancelBillResponse")]
        System.Threading.Tasks.Task RequestToCancelBillAsync(IsisAppTransportService.OrdBillingCancel billingCancel);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToIssueNewBill", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/R" +
            "equestToIssueNewBillResponse")]
        System.Threading.Tasks.Task<IsisAppTransportService.RequestToIssueNewBillResponse> RequestToIssueNewBillAsync(IsisAppTransportService.RequestToIssueNewBillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endScanRatingSheetCompleteToOutSide", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endScanRatingSheetCompleteToOutSideResponse")]
        System.Threading.Tasks.Task SendScanRatingSheetCompleteToOutSideAsync(string appRegisterID, string createdBy, string contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endScanOtherDocCompleteToOutSide", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/S" +
            "endScanOtherDocCompleteToOutSideResponse")]
        System.Threading.Tasks.Task SendScanOtherDocCompleteToOutSideAsync(string appRegisterID, string blaBranchCode, string createdBy, string contentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/U" +
            "pdateTaxPremium", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/U" +
            "pdateTaxPremiumResponse")]
        System.Threading.Tasks.Task UpdateTaxPremiumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etUnitPensionTotalGoalByAppNumber", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/G" +
            "etUnitPensionTotalGoalByAppNumberResponse")]
        System.Threading.Tasks.Task<IsisAppTransportService.PensionGoal> GetUnitPensionTotalGoalByAppNumberAsync(string appNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeBenefitEndorse", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeBenefitEndorseResponse")]
        System.Threading.Tasks.Task ChangeBenefitEndorseAsync(string policyNumber, IsisAppTransportService.BenefitItem[] benefitItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeAssureeNameEndorse", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeAssureeNameEndorseResponse")]
        System.Threading.Tasks.Task ChangeAssureeNameEndorseAsync(string idCardNumber, decimal idCardType, string preName, string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeAddressEndorse", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangeAddressEndorseResponse")]
        System.Threading.Tasks.Task ChangeAddressEndorseAsync(string policyNumber, IsisAppTransportService.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangePolicyStatus", ReplyAction="http://NewISISService/2012/ISISAppTransportService/IAppTransportServiceContract/C" +
            "hangePolicyStatusResponse")]
        System.Threading.Tasks.Task ChangePolicyStatusAsync(string policyNumber, string statusCode, string subStatusCode, string statusDetail, System.DateTime statusDate);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestToIssueNewPolicy", WrapperNamespace="http://NewISISService/2012/ISISAppTransportService", IsWrapped=true)]
    public partial class RequestToIssueNewPolicyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NewISISService/2012/ISISAppTransportService", Order=0)]
        public string appRegisterID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NewISISService/2012/ISISAppTransportService", Order=1)]
        public IsisAppTransportService.OrdBilling billing;
        
        public RequestToIssueNewPolicyRequest()
        {
        }
        
        public RequestToIssueNewPolicyRequest(string appRegisterID, IsisAppTransportService.OrdBilling billing)
        {
            this.appRegisterID = appRegisterID;
            this.billing = billing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestToIssueNewPolicyResponse", WrapperNamespace="http://NewISISService/2012/ISISAppTransportService", IsWrapped=true)]
    public partial class RequestToIssueNewPolicyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NewISISService/2012/ISISAppTransportService", Order=0)]
        public IsisAppTransportService.OrdBilling billing;
        
        public RequestToIssueNewPolicyResponse()
        {
        }
        
        public RequestToIssueNewPolicyResponse(IsisAppTransportService.OrdBilling billing)
        {
            this.billing = billing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestToIssueNewBill", WrapperNamespace="http://NewISISService/2012/ISISAppTransportService", IsWrapped=true)]
    public partial class RequestToIssueNewBillRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NewISISService/2012/ISISAppTransportService", Order=0)]
        public IsisAppTransportService.OrdBilling billing;
        
        public RequestToIssueNewBillRequest()
        {
        }
        
        public RequestToIssueNewBillRequest(IsisAppTransportService.OrdBilling billing)
        {
            this.billing = billing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestToIssueNewBillResponse", WrapperNamespace="http://NewISISService/2012/ISISAppTransportService", IsWrapped=true)]
    public partial class RequestToIssueNewBillResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NewISISService/2012/ISISAppTransportService", Order=0)]
        public IsisAppTransportService.OrdBilling billing;
        
        public RequestToIssueNewBillResponse()
        {
        }
        
        public RequestToIssueNewBillResponse(IsisAppTransportService.OrdBilling billing)
        {
            this.billing = billing;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IAppTransportServiceContractChannel : IsisAppTransportService.IAppTransportServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AppTransportServiceContractClient : System.ServiceModel.ClientBase<IsisAppTransportService.IAppTransportServiceContract>, IsisAppTransportService.IAppTransportServiceContract
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AppTransportServiceContractClient() : 
                base(AppTransportServiceContractClient.GetDefaultBinding(), AppTransportServiceContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ISISAppTransportServiceEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppTransportServiceContractClient(EndpointConfiguration endpointConfiguration) : 
                base(AppTransportServiceContractClient.GetBindingForEndpoint(endpointConfiguration), AppTransportServiceContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppTransportServiceContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AppTransportServiceContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppTransportServiceContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AppTransportServiceContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppTransportServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task ChangeAppFormStatusAsync(string appRegisterID, string status, string subStatus, string detail, System.DateTime requestDate, int gracePeriod, long isisDocID)
        {
            return base.Channel.ChangeAppFormStatusAsync(appRegisterID, status, subStatus, detail, requestDate, gracePeriod, isisDocID);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetAppFormContentByIDAsync(string appRegisterID)
        {
            return base.Channel.GetAppFormContentByIDAsync(appRegisterID);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetMoreContentByIDAsync(string responseID)
        {
            return base.Channel.GetMoreContentByIDAsync(responseID);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetContentByIDAsync(string contentID)
        {
            return base.Channel.GetContentByIDAsync(contentID);
        }
        
        public System.Threading.Tasks.Task SendCompleteContentStatusAsync(string appRegisterID)
        {
            return base.Channel.SendCompleteContentStatusAsync(appRegisterID);
        }
        
        public System.Threading.Tasks.Task SendReceiveContentStatusToOutSideAsync(string appRegisterID, string isisDocID, string receiveBranchCode, string createdBy, string contentID)
        {
            return base.Channel.SendReceiveContentStatusToOutSideAsync(appRegisterID, isisDocID, receiveBranchCode, createdBy, contentID);
        }
        
        public System.Threading.Tasks.Task<IsisAppTransportService.RequestToIssueNewPolicyResponse> RequestToIssueNewPolicyAsync(IsisAppTransportService.RequestToIssueNewPolicyRequest request)
        {
            return base.Channel.RequestToIssueNewPolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task RequestToCancelBillAsync(IsisAppTransportService.OrdBillingCancel billingCancel)
        {
            return base.Channel.RequestToCancelBillAsync(billingCancel);
        }
        
        public System.Threading.Tasks.Task<IsisAppTransportService.RequestToIssueNewBillResponse> RequestToIssueNewBillAsync(IsisAppTransportService.RequestToIssueNewBillRequest request)
        {
            return base.Channel.RequestToIssueNewBillAsync(request);
        }
        
        public System.Threading.Tasks.Task SendScanRatingSheetCompleteToOutSideAsync(string appRegisterID, string createdBy, string contentID)
        {
            return base.Channel.SendScanRatingSheetCompleteToOutSideAsync(appRegisterID, createdBy, contentID);
        }
        
        public System.Threading.Tasks.Task SendScanOtherDocCompleteToOutSideAsync(string appRegisterID, string blaBranchCode, string createdBy, string contentID)
        {
            return base.Channel.SendScanOtherDocCompleteToOutSideAsync(appRegisterID, blaBranchCode, createdBy, contentID);
        }
        
        public System.Threading.Tasks.Task UpdateTaxPremiumAsync()
        {
            return base.Channel.UpdateTaxPremiumAsync();
        }
        
        public System.Threading.Tasks.Task<IsisAppTransportService.PensionGoal> GetUnitPensionTotalGoalByAppNumberAsync(string appNumber)
        {
            return base.Channel.GetUnitPensionTotalGoalByAppNumberAsync(appNumber);
        }
        
        public System.Threading.Tasks.Task ChangeBenefitEndorseAsync(string policyNumber, IsisAppTransportService.BenefitItem[] benefitItems)
        {
            return base.Channel.ChangeBenefitEndorseAsync(policyNumber, benefitItems);
        }
        
        public System.Threading.Tasks.Task ChangeAssureeNameEndorseAsync(string idCardNumber, decimal idCardType, string preName, string firstName, string lastName)
        {
            return base.Channel.ChangeAssureeNameEndorseAsync(idCardNumber, idCardType, preName, firstName, lastName);
        }
        
        public System.Threading.Tasks.Task ChangeAddressEndorseAsync(string policyNumber, IsisAppTransportService.Address address)
        {
            return base.Channel.ChangeAddressEndorseAsync(policyNumber, address);
        }
        
        public System.Threading.Tasks.Task ChangePolicyStatusAsync(string policyNumber, string statusCode, string subStatusCode, string statusDetail, System.DateTime statusDate)
        {
            return base.Channel.ChangePolicyStatusAsync(policyNumber, statusCode, subStatusCode, statusDetail, statusDate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ISISAppTransportServiceEndpoint))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Mtom;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ISISAppTransportServiceEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://owssvr.bla.co.th/ISISAppTransportService.UAT/ISISAppTransportServiceRefere" +
                        "nce.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AppTransportServiceContractClient.GetBindingForEndpoint(EndpointConfiguration.ISISAppTransportServiceEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AppTransportServiceContractClient.GetEndpointAddress(EndpointConfiguration.ISISAppTransportServiceEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            ISISAppTransportServiceEndpoint,
        }
    }
}
